In [1]:
#instal libraries
#!pip install pandas openpyxl streamlit plotly

In [2]:
import pandas as pd

file = "Data/CAOPointsCharts2025.xlsx"

data2025 = pd.read_excel(file, skiprows=6)

print(data2025.head())
print(data2025.columns.tolist())
print(data2025.shape)

    CATEGORY (ISCED Description)  \
0    Business and administration
1  Humanities (except languages)
2                           Arts
3                           Arts
4                           Arts

                                        Course Title Course Code R1 Points  \
0                             International Business       AC120       278
1                                       Liberal Arts       AC137       293
2  First Year Art and Design  (Common Entry -  po...       AD101       515
3  Graphic Design and Moving Image Design (portfo...       AD102       538
4  Textile and Surface Design and Jewellery and O...       AD103       514

  R1 Random R2 Points R2 Random EOS Points EOS Random EOS Mid  Course Level  \
0       NaN       278       NaN        278        NaN     338             8
1       NaN       NaN       NaN        293        NaN     347             8
2       NaN       NaN       NaN        514        NaN     565             8
3       NaN       NaN       NaN        538        NaN     572             8
4       NaN       NaN       NaN        514        NaN     619             8

                                  HEI Test Interview  avp    v
0                    American College            NaN  avp  NaN
1                    American College            NaN  avp  NaN
2  National College of Art and Design              #  NaN  NaN
3  National College of Art and Design              #  NaN  NaN
4  National College of Art and Design              #  NaN  NaN
['CATEGORY (ISCED Description)', 'Course Title', 'Course Code', 'R1 Points', 'R1 Random', 'R2 Points', 'R2 Random', 'EOS Points', 'EOS Random', 'EOS Mid', 'Course Level', 'HEI', 'Test Interview', 'avp', 'v']
(1376, 15)

In [3]:
data2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1376 entries, 0 to 1375
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   CATEGORY (ISCED Description)  1375 non-null   object
 1   Course Title                  1376 non-null   object
 2   Course Code                   1376 non-null   object
 3   R1 Points                     1359 non-null   object
 4   R1 Random                     27 non-null     object
 5   R2 Points                     302 non-null    object
 6   R2 Random                     31 non-null     object
 7   EOS Points                    1363 non-null   object
 8   EOS Random                    44 non-null     object
 9   EOS Mid                       1362 non-null   object
 10  Course Level                  1376 non-null   int64
 11  HEI                           1376 non-null   object
 12  Test Interview                111 non-null    object
 13  avp                           174 non-null    object
 14  v                             23 non-null     object
dtypes: int64(1), object(14)
memory usage: 161.4+ KB

In [4]:
data2025.isna().sum()

CATEGORY (ISCED Description)       1
Course Title                       0
Course Code                        0
R1 Points                         17
R1 Random                       1349
R2 Points                       1074
R2 Random                       1345
EOS Points                        13
EOS Random                      1332
EOS Mid                           14
Course Level                       0
HEI                                0
Test Interview                  1265
avp                             1202
v                               1353
dtype: int64

In [5]:
data2025["AQA"] = (
    data2025["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2025["Year"] = 2025

data2025.head()

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,R1 Random,R2 Points,R2 Random,EOS Points,EOS Random,EOS Mid,Course Level,HEI,Test Interview,avp,v,AQA,Year
0,Business and administration,International Business,AC120,278,NaN,278,NaN,278,NaN,338,8,American College,NaN,avp,NaN,False,2025
1,Humanities (except languages),Liberal Arts,AC137,293,NaN,NaN,NaN,293,NaN,347,8,American College,NaN,avp,NaN,False,2025
2,Arts,First Year Art and Design (Common Entry - po...,AD101,515,NaN,NaN,NaN,514,NaN,565,8,National College of Art and Design,#,NaN,NaN,False,2025
3,Arts,Graphic Design and Moving Image Design (portfo...,AD102,538,NaN,NaN,NaN,538,NaN,572,8,National College of Art and Design,#,NaN,NaN,False,2025
4,Arts,Textile and Surface Design and Jewellery and O...,AD103,514,NaN,NaN,NaN,514,NaN,619,8,National College of Art and Design,#,NaN,NaN,False,2025

In [6]:
data2025_clean = data2025.drop(
    columns=[
        "R1 Random",
        "R2 Points",
        "R2 Random",
        "EOS Points",
        "EOS Random",
        "EOS Mid",
        "Test Interview",
        "avp",
        "v"
    ]
)

data2025_clean.head()

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Business and administration,International Business,AC120,278,8,American College,False,2025
1,Humanities (except languages),Liberal Arts,AC137,293,8,American College,False,2025
2,Arts,First Year Art and Design (Common Entry - po...,AD101,515,8,National College of Art and Design,False,2025
3,Arts,Graphic Design and Moving Image Design (portfo...,AD102,538,8,National College of Art and Design,False,2025
4,Arts,Textile and Surface Design and Jewellery and O...,AD103,514,8,National College of Art and Design,False,2025

### Historic Data ###

In [8]:
file = "Data/CAOPointsCharts2024.xlsx"

data2024 = pd.read_excel(file, skiprows=5)

print(data2024.head())
print(data2024.columns.tolist())
print(data2024.shape)

    CATEGORY (ISCED Description)  \
0    Business and administration
1  Humanities (except languages)
2                           Arts
3                           Arts
4                           Arts

                                        Course Title Course Code R1 Points  \
0                             International Business       AC120       269
1                                       Liberal Arts       AC137       254
2  First Year Art and Design  (Common Entry -  po...       AD101       512
3  Graphic Design and Moving Image Design (portfo...       AD102       694
4  Textile and Surface Design and Jewellery and O...       AD103       568

  R1 Random R2 Points R2 Random EOS Points EOS Random  EOS Midpoints  \
0       NaN       269       NaN        269        NaN          281.0
1       NaN       254       NaN        254        NaN          254.0
2       NaN       503       NaN        503        NaN          587.0
3       NaN       NaN       NaN        694        NaN          694.0
4       NaN       NaN       NaN        568        NaN          607.0

   Course Level                                 HEI Test Interview  avp    v
0             8                    American College            NaN  avp  NaN
1             8                    American College            NaN  avp  NaN
2             8  National College of Art and Design              #  NaN  NaN
3             8  National College of Art and Design              #  NaN  NaN
4             8  National College of Art and Design              #  NaN  NaN
['CATEGORY (ISCED Description)', 'Course Title', 'Course Code', 'R1 Points', 'R1 Random', 'R2 Points', 'R2 Random', 'EOS Points', 'EOS Random', 'EOS Midpoints', 'Course Level', 'HEI', 'Test Interview', 'avp', 'v']
(1396, 15)

In [9]:
data2024["AQA"] = (
    data2024["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2024["Year"] = 2024

data2024.head()

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,R1 Random,R2 Points,R2 Random,EOS Points,EOS Random,EOS Midpoints,Course Level,HEI,Test Interview,avp,v,AQA,Year
0,Business and administration,International Business,AC120,269,NaN,269,NaN,269,NaN,281.0,8,American College,NaN,avp,NaN,False,2024
1,Humanities (except languages),Liberal Arts,AC137,254,NaN,254,NaN,254,NaN,254.0,8,American College,NaN,avp,NaN,False,2024
2,Arts,First Year Art and Design (Common Entry - po...,AD101,512,NaN,503,NaN,503,NaN,587.0,8,National College of Art and Design,#,NaN,NaN,False,2024
3,Arts,Graphic Design and Moving Image Design (portfo...,AD102,694,NaN,NaN,NaN,694,NaN,694.0,8,National College of Art and Design,#,NaN,NaN,False,2024
4,Arts,Textile and Surface Design and Jewellery and O...,AD103,568,NaN,NaN,NaN,568,NaN,607.0,8,National College of Art and Design,#,NaN,NaN,False,2024

In [10]:
data2024_clean = data2024.drop(
    columns=[
        "R1 Random",
        "R2 Points",
        "R2 Random",
        "EOS Points",
        "EOS Random",
        "EOS Midpoints",
        "Test Interview",
        "avp",
        "v"
    ]
)

data2024_clean.head()

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Business and administration,International Business,AC120,269,8,American College,False,2024
1,Humanities (except languages),Liberal Arts,AC137,254,8,American College,False,2024
2,Arts,First Year Art and Design (Common Entry - po...,AD101,512,8,National College of Art and Design,False,2024
3,Arts,Graphic Design and Moving Image Design (portfo...,AD102,694,8,National College of Art and Design,False,2024
4,Arts,Textile and Surface Design and Jewellery and O...,AD103,568,8,National College of Art and Design,False,2024

In [11]:
#read in data
file = "Data/CAOPointsCharts2023.xlsx"

data2023 = pd.read_excel(file, skiprows=7)

print(data2023.head())
#print(data2023.columns.tolist())
#print(data2023.shape)

#add in "all qualified aplicants" and "year" columns
data2023["AQA"] = (
    data2023["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2023["Year"] = 2023

#data2023.head()

#remove unnessessary rows
data2023_clean = data2023.drop(
    columns=[
        "R1 Random",
        "R2 Points",
        "R2 Random",
        "EOS Points",
        "EOS Random",
        "EOS Midpoints",
        "Test Interview",
        "avp",
        "v"
    ]
)

data2023_clean.head()

    CATEGORY (ISCED Description)  \
0    Business and administration
1  Humanities (except languages)
2                           Arts
3                           Arts
4                           Arts

                                        Course Title Course Code R1 Points  \
0                             International Business       AC120       218
1                                       Liberal Arts       AC137       269
2   First Year Art & Design (Portfolio,Common Entry)       AD101       559
3  Graphic Design and Moving Image Design (Portfo...       AD102       638
4  Textile & Surface Design and Jewellery & Objec...       AD103       558

  R1 Random R2 Points R2 Random EOS Points EOS Random EOS Midpoints  \
0       NaN       NaN       NaN        218        NaN           303
1       NaN       NaN       NaN        269        NaN           305
2       NaN       NaN       NaN        559        NaN           613
3       NaN       NaN       NaN        638        NaN           648
4       NaN       NaN       NaN        564        NaN           593

   Course Level                                 HEI Test Interview  avp    v
0             8                    American College            NaN  NaN  NaN
1             8                    American College            NaN  NaN  NaN
2             8  National College of Art and Design              #  NaN  NaN
3             8  National College of Art and Design              #  NaN  NaN
4             8  National College of Art and Design              #  NaN  NaN

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Business and administration,International Business,AC120,218,8,American College,False,2023
1,Humanities (except languages),Liberal Arts,AC137,269,8,American College,False,2023
2,Arts,"First Year Art & Design (Portfolio,Common Entry)",AD101,559,8,National College of Art and Design,False,2023
3,Arts,Graphic Design and Moving Image Design (Portfo...,AD102,638,8,National College of Art and Design,False,2023
4,Arts,Textile & Surface Design and Jewellery & Objec...,AD103,558,8,National College of Art and Design,False,2023

In [12]:
#read in data
file = "Data/CAOPointsCharts2022.xlsx"

data2022 = pd.read_excel(file, skiprows=5)

print(data2022.head())
#print(data2022.columns.tolist())
#print(data2022.shape)

#add in "all qualified aplicants" and "year" columns
data2022["AQA"] = (
    data2022["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2022["Year"] = 2022

#data2022.head()

#remove unnessessary rows
data2022_clean = data2022.drop(
    columns=[
        "R1 Random",
        "R2 Points",
        "R2 Random",
        "EOS Points",
        "EOS Random",
        "EOS Midpoints",
        "Test Interview",
        "avp",
        "v"
    ]
)

data2022_clean.head()

      CATEGORY (ISCED Description)                     Course Title  \
0                             Arts  Music and Instrument Technology
1                           Health              Pharmacy Technician
2                           Health                   Dental Nursing
3  Biological and related sciences                  Applied Science
4      Business and administration                         Business

  Course Code R1 Points R1 Random R2 Points R2 Random EOS Points EOS Random  \
0       AL605       189       NaN       NaN       NaN        189        NaN
1       AL630       261       NaN       NaN       NaN        261        NaN
2       AL631       376       NaN       NaN       NaN        356        NaN
3       AL632       276       NaN       NaN       NaN        276        NaN
4       AL650       129       NaN       NaN       NaN        118        NaN

   EOS Midpoints  Course Level                              HEI  \
0          370.0             6  Athlone Institute of Technology
1          367.0             6  Athlone Institute of Technology
2          409.0             6  Athlone Institute of Technology
3          366.0             6  Athlone Institute of Technology
4          392.0             6  Athlone Institute of Technology

  Test Interview  avp    v
0            NaN  NaN  NaN
1            NaN  NaN  NaN
2            NaN  NaN  NaN
3            NaN  NaN  NaN
4            NaN  avp  NaN

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Arts,Music and Instrument Technology,AL605,189,6,Athlone Institute of Technology,False,2022
1,Health,Pharmacy Technician,AL630,261,6,Athlone Institute of Technology,False,2022
2,Health,Dental Nursing,AL631,376,6,Athlone Institute of Technology,False,2022
3,Biological and related sciences,Applied Science,AL632,276,6,Athlone Institute of Technology,False,2022
4,Business and administration,Business,AL650,129,6,Athlone Institute of Technology,False,2022

In [13]:
#read in data
file = "Data/CAOPointsCharts2021.xlsx"

data2021 = pd.read_excel(file, skiprows=11)

print(data2021.head())
#print(data2021.columns.tolist())
#print(data2021.shape)

#add in "all qualified aplicants" and "year" columns
data2021["AQA"] = (
    data2021["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2021["Year"] = 2021

#data2021.head()

#remove unnessessary rows
data2021_clean = data2021.drop(
    columns=[
        "R1 Random",
        "R2 Points",
        "R2 Points ",
        "R2 Random",
        "EOS Points",
        "EOS Random",
        "EOS Midpoints",
        "Test Interview",
        "Test/Interview",
        "avp",
        "AVP",
        "v"
    ],
    errors="ignore"
      )

data2021_clean.head()

         CATEGORY (ISCED Description)                     Course Title  \
0  Engineering and engineering trades  Music and Instrument Technology
1                              Health              Pharmacy Technician
2                              Health                   Dental Nursing
3     Biological and related sciences                  Applied Science
4         Business and administration                         Business

  Course Code R1 Points R1 Random R2 Points  R2 Random EOS Points EOS Random  \
0       AL605       211       NaN        NaN       NaN        211        NaN
1       AL630       308       NaN        NaN       NaN        308        NaN
2       AL631       311       NaN        NaN       NaN        311        NaN
3       AL632       297       NaN        NaN       NaN        297        NaN
4       AL650       AQA       NaN        AQA       NaN        AQA        NaN

  EOS Midpoints  Course Level                              HEI Test/Interview  \
0           319             6  Athlone Institute of Technology            NaN
1           409             6  Athlone Institute of Technology            NaN
2           400             6  Athlone Institute of Technology            NaN
3           454             6  Athlone Institute of Technology            NaN
4           351             6  Athlone Institute of Technology            NaN

   AVP    v
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN
4  avp  NaN

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Engineering and engineering trades,Music and Instrument Technology,AL605,211,6,Athlone Institute of Technology,False,2021
1,Health,Pharmacy Technician,AL630,308,6,Athlone Institute of Technology,False,2021
2,Health,Dental Nursing,AL631,311,6,Athlone Institute of Technology,False,2021
3,Biological and related sciences,Applied Science,AL632,297,6,Athlone Institute of Technology,False,2021
4,Business and administration,Business,AL650,AQA,6,Athlone Institute of Technology,True,2021

In [14]:
#read in data
file = "Data/CAOPointsCharts2020.xlsx"

data2020 = pd.read_excel(file, skiprows=10)

print(data2020.head())
#print(data2020.columns.tolist())
#print(data2020.shape)

# Select and rename the columns we need
data2020_clean = data2020[
    [
        "CATEGORY (i.e.ISCED description)",
        "COURSE TITLE",
        "COURSE CODE2",
        "R1 POINTS",
        "LEVEL",
        "HEI"
    ]
].copy()

data2020_clean.columns = [
    "Category",
    "Course Title",
    "Course Code",
    "R1 Points",
    "Course Level",
    "HEI"
]

#add in "all qualified aplicants" and "year" columns
data2020_clean["AQA"] = (
    data2020_clean["R1 Points"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("AQA")
)

data2020_clean["Year"] = 2020

data2020_clean.head()

  CATEGORY (i.e.ISCED description)  \
0      Business and administration
1    Humanities (except languages)
2                             Arts
3                             Arts
4                             Arts

                                        COURSE TITLE COURSE CODE2 R1 POINTS  \
0                             International Business        AC120       209
1                                       Liberal Arts        AC137       252
2   First Year Art & Design (Common Entry,portfolio)        AD101  #+matric
3  Graphic Design and Moving Image Design (portfo...        AD102  #+matric
4  Textile & Surface Design and Jewellery & Objec...        AD103  #+matric

  R1 Random * R2 POINTS R2 Random*       EOS EOS Random * EOS Mid-point  ...  \
0         NaN       NaN        NaN       209          NaN           280  ...
1         NaN       NaN        NaN       252          NaN           270  ...
2         NaN       NaN        NaN  #+matric          NaN      #+matric  ...
3         NaN       NaN        NaN  #+matric          NaN      #+matric  ...
4         NaN       NaN        NaN  #+matric          NaN      #+matric  ...

   avp    v Column1 Column2 Column3  Column4  Column5  Column6  Column7  \
0  NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN      NaN
1  NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN      NaN
2  NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN      NaN
3  NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN      NaN
4  NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN      NaN

   Column8
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

[5 rows x 23 columns]

,Category,Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Business and administration,International Business,AC120,209,8,American College,False,2020
1,Humanities (except languages),Liberal Arts,AC137,252,8,American College,False,2020
2,Arts,"First Year Art & Design (Common Entry,portfolio)",AD101,#+matric,8,National College of Art and Design,False,2020
3,Arts,Graphic Design and Moving Image Design (portfo...,AD102,#+matric,8,National College of Art and Design,False,2020
4,Arts,Textile & Surface Design and Jewellery & Objec...,AD103,#+matric,8,National College of Art and Design,False,2020

In [15]:
data2020_clean["R1 Points"].value_counts(dropna=False).head(15)

R1 Points
NaN         27
AQA         26
300         26
270         18
280         18
260         16
498         16
308         15
309         15
252         15
307         14
290         13
#+matric    13
510         12
244         12
Name: count, dtype: int64

In [16]:
data2020_clean[
    data2020_clean["R1 Points"].astype(str).str.strip() == "#+matric"
][
    ["Course Code", "Course Title", "Course Level", "HEI"]
]

,Course Code,Course Title,Course Level,HEI
2,AD101,"First Year Art & Design (Common Entry,portfolio)",8,National College of Art and Design
3,AD102,Graphic Design and Moving Image Design (portfo...,8,National College of Art and Design
4,AD103,Textile & Surface Design and Jewellery & Objec...,8,National College of Art and Design
5,AD202,Education & Design or Fine Art (Second Level T...,8,National College of Art and Design
6,AD204,Fine Art (portfolio),8,National College of Art and Design
7,AD211,Fashion Design (portfolio),8,National College of Art and Design
8,AD212,Product Design (portfolio),8,National College of Art and Design
10,AD217,Illustration (portfolio),8,National College of Art and Design
11,AD222,Interaction Design (portfolio),8,National College of Art and Design
195,CR210,"Contemporary Applied Art (Ceramics, Glass, Tex...",8,Cork Institute of Technology
196,CR220,Fine Art at CIT Crawford College of Art and De...,8,Cork Institute of Technology
197,CR225,Photography with New Media,8,Cork Institute of Technology
223,CR600,Visual Communications,8,Cork Institute of Technology

## Decided to look only at last 5 years (up to 2021) as unusual circumstances in 2020 with COVID (predicted grades)

# Creating larger dataset

In [19]:
all_cao_data = pd.concat(
    [
        data2021_clean,
        data2022_clean,
        data2023_clean,
        data2024_clean,
        data2025_clean
    ],
    ignore_index=True
)

all_cao_data.head()

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
0,Engineering and engineering trades,Music and Instrument Technology,AL605,211,6,Athlone Institute of Technology,False,2021
1,Health,Pharmacy Technician,AL630,308,6,Athlone Institute of Technology,False,2021
2,Health,Dental Nursing,AL631,311,6,Athlone Institute of Technology,False,2021
3,Biological and related sciences,Applied Science,AL632,297,6,Athlone Institute of Technology,False,2021
4,Business and administration,Business,AL650,AQA,6,Athlone Institute of Technology,True,2021

In [20]:
#check years present
print(all_cao_data.shape)
print(all_cao_data["Year"].value_counts().sort_index())

(7033, 8)
Year
2021    1451
2022    1399
2023    1411
2024    1396
2025    1376
Name: count, dtype: int64

In [21]:
#check cols
print(all_cao_data.columns.tolist())

['CATEGORY (ISCED Description)', 'Course Title', 'Course Code', 'R1 Points', 'Course Level', 'HEI', 'AQA', 'Year']

In [22]:
#testing one course
all_cao_data[all_cao_data["Course Code"] == "AC120"]

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year
273,Business and administration,International Business,AC120,294,8,American College,False,2021
1781,Business and administration,International Business,AC120,218,8,American College,False,2022
2850,Business and administration,International Business,AC120,218,8,American College,False,2023
4261,Business and administration,International Business,AC120,269,8,American College,False,2024
5657,Business and administration,International Business,AC120,278,8,American College,False,2025

In [23]:
#checking to see if any courses had 0 points as the requirment 
all_cao_data[all_cao_data["R1 Points"] == 0]

Empty DataFrame
Columns: [CATEGORY (ISCED Description), Course Title, Course Code, R1 Points, Course Level, HEI, AQA, Year]
Index: []

In [24]:
#changing all AQA values to 0 points- information will still be retained by AQA column
all_cao_data["Points"] =  pd.to_numeric(
    all_cao_data["R1 Points"],
    errors="coerce"
).astype("Int64")

all_cao_data.loc[all_cao_data["AQA"], "Points"] = 0
#show
all_cao_data.head(20)

,CATEGORY (ISCED Description),Course Title,Course Code,R1 Points,Course Level,HEI,AQA,Year,Points
0,Engineering and engineering trades,Music and Instrument Technology,AL605,211,6,Athlone Institute of Technology,False,2021,211
1,Health,Pharmacy Technician,AL630,308,6,Athlone Institute of Technology,False,2021,308
2,Health,Dental Nursing,AL631,311,6,Athlone Institute of Technology,False,2021,311
3,Biological and related sciences,Applied Science,AL632,297,6,Athlone Institute of Technology,False,2021,297
4,Business and administration,Business,AL650,AQA,6,Athlone Institute of Technology,True,2021,0
5,Personal services,Culinary Arts,AL660,AQA,6,Athlone Institute of Technology,True,2021,0
6,Personal services,Bar Supervision,AL661,AQA,6,Athlone Institute of Technology,True,2021,0
7,Personal services,Business (Sport and Recreation),AL663,AQA,6,Athlone Institute of Technology,True,2021,0
8,Information and Communication Technologies (ICTs),Computer Engineering for Network Infrastructure,AL701,207,7,Athlone Institute of Technology,False,2021,207
9,Information and Communication Technologies (ICTs),Software Design in Artificial Intelligence for...,AL702,220,7,Athlone Institute of Technology,False,2021,220
10,Information and Communication Technologies (ICTs),Software Design for Virtual Reality and Gaming,AL703,211,7,Athlone Institute of Technology,False,2021,211
11,Information and Communication Technologies (ICTs),Computer Engineering,AL704,210,7,Athlone Institute of Technology,False,2021,210
12,Information and Communication Technologies (ICTs),Software Design for Mobile Apps and Connected ...,AL705,250,7,Athlone Institute of Technology,False,2021,250
13,Engineering and engineering trades,Mechanical Engineering,AL710,243,7,Athlone Institute of Technology,False,2021,243
14,Engineering and engineering trades,Mechanical Engineering and Renewable Energy,AL711,238,7,Athlone Institute of Technology,False,2021,238
15,Engineering and engineering trades,Automation and Robotics,AL712,247,7,Athlone Institute of Technology,False,2021,247
16,Engineering and engineering trades,Engineering (Common Entry to Automation and Ro...,AL713,226,7,Athlone Institute of Technology,False,2021,226
17,Engineering and engineering trades,Music and Sound Engineering,AL718,242,7,Athlone Institute of Technology,False,2021,242
18,Architecture and construction,Civil Engineering,AL721,242,7,Athlone Institute of Technology,False,2021,242
19,Biological and related sciences,Biotechnology,AL730,261,7,Athlone Institute of Technology,False,2021,261

In [25]:
#changing catergory column title and HEI
all_cao_data = all_cao_data.rename(
    columns={"CATEGORY (ISCED Description)": "Category", "HEI":"HE Institution"}
)

In [26]:
all_cao_data.head()

,Category,Course Title,Course Code,R1 Points,Course Level,HE Institution,AQA,Year,Points
0,Engineering and engineering trades,Music and Instrument Technology,AL605,211,6,Athlone Institute of Technology,False,2021,211
1,Health,Pharmacy Technician,AL630,308,6,Athlone Institute of Technology,False,2021,308
2,Health,Dental Nursing,AL631,311,6,Athlone Institute of Technology,False,2021,311
3,Biological and related sciences,Applied Science,AL632,297,6,Athlone Institute of Technology,False,2021,297
4,Business and administration,Business,AL650,AQA,6,Athlone Institute of Technology,True,2021,0

In [27]:
#fixing duplicate categories...
#working out which category has most years of data
year_columns = [2021, 2022, 2023, 2024, 2025]

category_choice = (
    all_cao_data
    .groupby(["Course Code", "Category"], dropna=False)
    ["Points"]
    .apply(lambda x: x.notna().sum())
    .reset_index(name="Years_with_data")
)

category_choice.head()

  Course Code                       Category  Years_with_data
0       AC120    Business and administration                5
1       AC137  Humanities (except languages)                5
2       AD101                           Arts                5
3       AD102                           Arts                5
4       AD103                           Arts                5

In [28]:
#choose category with most years of data
category_choice = (
    category_choice
    .sort_values(
        ["Course Code", "Years_with_data"],
        ascending=[True, False]
    )
    .drop_duplicates("Course Code")
)

In [29]:
#lookup 
category_lookup = category_choice.set_index("Course Code")["Category"]

In [30]:
#replacing category throughout 
all_cao_data["Category"] = (
    all_cao_data["Course Code"]
    .map(category_lookup)
)

In [31]:
#checking one course
all_cao_data[
    all_cao_data["Course Code"] == "CK412"
][
    ["Course Code", "Course Title", "Category", "Year", "Points"]
].sort_values("Year")

,Course Code,Course Title,Category,Year,Points
255,CK412,Agricultural Science,Interdisciplinary programmes and qualification...,2021,506
1763,CK412,Agricultural Science,Interdisciplinary programmes and qualification...,2022,487
3139,CK412,Agricultural Science,Interdisciplinary programmes and qualification...,2023,496
4541,CK412,Agricultural Science,Interdisciplinary programmes and qualification...,2024,446
5929,CK412,Agricultural Science,Interdisciplinary programmes and qualification...,2025,484

In [32]:
#pivot on year for trend graphs- using course code as identifier
course_history = all_cao_data.pivot_table(
    index=["Course Code",
        "HE Institution",
        "Course Level",
        "Category"
          ],
    columns="Year",
    values="Points",
    aggfunc="first"
).reset_index()

course_history.head()

Year,Course Code,HE Institution,Course Level,Category,2021,2022,2023,2024,2025
0,AC120,American College,8,Business and administration,294,218,218,269,278
1,AC137,American College,8,Humanities (except languages),271,244,269,254,293
2,AD101,National College of Art and Design,8,Arts,554,529,559,512,515
3,AD102,National College of Art and Design,8,Arts,538,506,638,694,538
4,AD103,National College of Art and Design,8,Arts,505,484,558,568,514

In [33]:
# get course titles back (issue with duplicate titles with slight changes)
# Get the 2025 course titles
course_titles = data2025_clean[
    ["Course Code", "Course Title"]
].drop_duplicates("Course Code")

# Add the 2025 course titles to the historical data
course_history = course_history.merge(
    course_titles,
    on="Course Code",
    how="inner"    #changed to inner as only want 2025 list... others may be obsolete courses
)

# Move Course Title beside Course Code
course_history = course_history[
    [
        "Course Code",
        "Course Title",
        "HE Institution",
        "Course Level",
        "Category",
        2021,
        2022,
        2023,
        2024,
        2025
    ]
]

course_history.head()

,Course Code,Course Title,HE Institution,Course Level,Category,2021,2022,2023,2024,2025
0,AC120,International Business,American College,8,Business and administration,294,218,218,269,278
1,AC137,Liberal Arts,American College,8,Humanities (except languages),271,244,269,254,293
2,AD101,First Year Art and Design (Common Entry - po...,National College of Art and Design,8,Arts,554,529,559,512,515
3,AD102,Graphic Design and Moving Image Design (portfo...,National College of Art and Design,8,Arts,538,506,638,694,538
4,AD103,Textile and Surface Design and Jewellery and O...,National College of Art and Design,8,Arts,505,484,558,568,514

In [67]:
course_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1425 entries, 0 to 1424
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Course Code     1425 non-null   object
 1   Course Title    1425 non-null   object
 2   HE Institution  1425 non-null   object
 3   Course Level    1425 non-null   int64
 4   Category        1425 non-null   object
 5   2021            637 non-null    Int64
 6   2022            755 non-null    Int64
 7   2023            1267 non-null   Int64
 8   2024            1321 non-null   Int64
 9   2025            1356 non-null   Int64
dtypes: Int64(5), int64(1), object(4)
memory usage: 118.4+ KB

In [69]:
#export data to csv
data2025_clean.to_csv(
    "Data/CAO_2025_clean.csv",
    index=False
)

course_history.to_csv(
    "Data/CAO_course_history.csv",
    index=False
)